/**
 * Performance harness (Y-PRF-04).
 *
 * Measures the store-level editor budgets from plan.md Section 14 against a
 * 500-element document and asserts each stays under budget. When run with
 * `PERF_BASELINE_WRITE=1` it also rewrites `docs/0.2.0v/perf-baseline.md`
 * with the measured numbers (the testing-rules harness contract); in CI the
 * flag is unset so the doc is never churned.
 *
 * Three budgets are measurable headlessly because they are pure
 * JS/data work: undo/redo patch round-trip, `.dtw` serialize (save), and
 * parse+migrate+validate (open). The render-bound budgets (drag fps, theme
 * toggle, breakpoint switch, cold-start) need the running app + React
 * DevTools profiler and are documented as methodology in the baseline doc.
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { afterAll, describe, expect, it } from 'vitest'

import { migrate } from '../../src/document/migrations'
import type { ContainerNode, Document, TextNode } from '../../src/document/types'
import { dispatch, redo, undo } from '../../src/store/dispatch'
import {
  CURRENT_DOCUMENT_VERSION,
  createBlankDocument,
  useDocumentStore,
} from '../../src/store/documentStore'
import { useHistoryStore } from '../../src/store/historyStore'

const ELEMENT_COUNT = 500
const WARMUP = 5
const ITERATIONS = 30

/** A flat 500-child document — the Section 14 reference size for save/open/drag. */
function build500ElementDocument(): Document {
  const children: TextNode[] = Array.from({ length: ELEMENT_COUNT }, (_, i) => ({
    id: `perf-${i}`,
    type: 'text',
    tag: 'p',
    content: `Element ${i}`,
    style: { base: {} },
  }))
  const root: ContainerNode = {
    id: 'perf-root',
    type: 'container',
    style: { base: {} },
    layout: { base: { mode: 'flex', direction: 'column' } },
    children,
  }
  return { ...createBlankDocument('Perf 500'), tree: root }
}

/** Median wall-clock duration (ms) of `fn` over ITERATIONS runs after warmup. */
function medianMs(fn: () => void): number {
  for (let i = 0; i < WARMUP; i += 1) fn()
  const samples: number[] = []
  for (let i = 0; i < ITERATIONS; i += 1) {
    const start = performance.now()
    fn()
    samples.push(performance.now() - start)
  }
  samples.sort((a, b) => a - b)
  return samples[Math.floor(samples.length / 2)]
}

interface Measurement {
  readonly label: string
  readonly budgetMs: number
  readonly measuredMs: number
}

const results: Measurement[] = []
const record = (label: string, budgetMs: number, measuredMs: number): number => {
  results.push({ label, budgetMs, measuredMs })
  return measuredMs
}

describe('Y-PRF-04 — editor performance budgets (500 elements)', () => {
  const doc = build500ElementDocument()
  const json = JSON.stringify(doc)

  it(`saves (.dtw serialize) under 500 ms`, () => {
    const ms = record(
      'Project save (.dtw serialize, 500 el)',
      500,
      medianMs(() => {
        JSON.stringify(doc)
      })
    )
    expect(ms).toBeLessThan(500)
  })

  it(`opens (parse + migrate + validate) under 1.5 s`, () => {
    const ms = record(
      'Project open (parse + migrate + validate, 500 el)',
      1500,
      medianMs(() => {
        migrate(JSON.parse(json), CURRENT_DOCUMENT_VERSION, CURRENT_DOCUMENT_VERSION)
      })
    )
    expect(ms).toBeLessThan(1500)
  })

  it(`undo/redo round-trip under 16 ms`, () => {
    useDocumentStore.setState({ document: doc, isDirty: false })
    useHistoryStore.setState({ past: [], future: [] })
    // Seed one undoable edit, then ping-pong it so both stacks stay primed.
    dispatch({ kind: 'updateNode', id: 'perf-250', path: ['content'], value: 'edited' })

    const ms = record(
      'Undo/redo round-trip (500 el)',
      16,
      medianMs(() => {
        undo()
        redo()
      })
    )
    expect(ms).toBeLessThan(16)
  })

  afterAll(() => {
    if (process.env.PERF_BASELINE_WRITE !== '1') return
    const path = fileURLToPath(new URL('../../docs/0.2.0v/perf-baseline.md', import.meta.url))
    writeFileSync(path, renderBaseline(results), 'utf8')
  })
})

/** Render the full Section 14 baseline doc, filling in the harness-measured rows. */
function renderBaseline(measured: readonly Measurement[]): string {
  const date = new Date().toISOString().slice(0, 10)
  const row = (m: Measurement): string => {
    const pass = m.measuredMs < m.budgetMs ? '✅' : '❌'
    return `| ${m.label} | < ${m.budgetMs} ms | ${m.measuredMs.toFixed(2)} ms | ${pass} |`
  }
  return `# Performance Baseline — v0.2.0 (Y-PRF-04)

> Generated by \`tests/perf/editorPerf.test.ts\` (\`PERF_BASELINE_WRITE=1 npm run test -- editorPerf\`).
> Last run: ${date}. Reference document: ${ELEMENT_COUNT} elements. Median of ${ITERATIONS} iterations (${WARMUP} warmup).

## Harness-measured (store / data layer)

These three budgets are pure JS/data work and are measured headlessly by the
Vitest harness on every run, so regressions trip the suite, not just the doc.

| Metric | Budget | Measured | Status |
| ------ | ------ | -------- | ------ |
${measured.map(row).join('\n')}

## In-app (render layer) — methodology

The render-bound budgets need the running Electron app and the React DevTools
profiler; they are not measured by the headless harness. Procedure:

1. \`npm run dev\`, open the Portfolio template, switch the canvas to the
   500-element stress fixture.
2. **Drag (100 / 500 elements):** record a drag in the profiler; read the
   committed-frames FPS. Budget: 60 fps @ 100 el, ≥ 45 fps @ 500 el. Held by
   \`React.memo\` on \`CanvasNode\` (Y-PRF-01) + stable selectors (Y-PRF-02).
3. **Theme toggle:** time \`data-theme\` flip to repaint. Budget < 100 ms.
4. **Breakpoint switch:** time desktop→mobile canvas reflow. Budget < 200 ms.
5. **Cold-start:** app launch → interactive. Budget < 3 s.
6. **Layers tree (500 nodes):** scroll; confirm \`react-arborist\` windowing
   keeps it at 60 fps (Y-PRF-03).

| Metric | Budget | Measured | Status |
| ------ | ------ | -------- | ------ |
| Element drag (100 elements) | 60 fps | _pending instrumented run_ | — |
| Element drag (500 elements) | ≥ 45 fps | _pending instrumented run_ | — |
| Theme toggle on canvas | < 100 ms | _pending instrumented run_ | — |
| Breakpoint switch | < 200 ms | _pending instrumented run_ | — |
| Layers tree scroll (500 nodes) | 60 fps | _pending instrumented run_ | — |
| Cold-start to interactive | < 3 s | _pending instrumented run_ | — |
`
}
