/**
 * Coverage for the two I-EXP-03 export options that don't have their own
 * dedicated stage:
 *
 *   - `theme: 'auto' | 'light' | 'dark'` — stamps `data-theme` on `<html>`.
 *   - `includeSourceComments: boolean` — prepends a single-line banner to
 *     each output file (HTML / CSS / optional JS).
 *
 * Both transformations survive minify because the theme attr is applied
 * before the gate and the banner is applied after minify.
 */

import { describe, it, expect, beforeEach, vi } from 'vitest'
import JSZip from 'jszip'
import { exportProject } from '../../src/export'
import { PORTFOLIO_DOCUMENT } from '../fixtures/portfolioDocument'

interface MockIpcResult {
  success: boolean
  filePath?: string
  error?: string
}

function setupElectronAPI(zipResult: MockIpcResult): { capturedBuffer: ArrayBuffer | null } {
  const captured = { capturedBuffer: null as ArrayBuffer | null }
  vi.stubGlobal('window', {
    electronAPI: {
      exportZip: vi.fn(async (buf: ArrayBuffer) => {
        captured.capturedBuffer = buf
        return zipResult
      }),
    },
  })
  return captured
}

async function readEntries(buf: ArrayBuffer): Promise<{ html: string; css: string; js?: string }> {
  const zip = await JSZip.loadAsync(buf)
  const out: { html: string; css: string; js?: string } = {
    html: await zip.file('index.html')!.async('string'),
    css: await zip.file('styles.css')!.async('string'),
  }
  const jsEntry = zip.file('scripts.js')
  if (jsEntry) out.js = await jsEntry.async('string')
  return out
}

describe('theme option (I-EXP-03)', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    vi.unstubAllGlobals()
  })

  it('auto is the default and does not stamp data-theme', async () => {
    const stub = setupElectronAPI({ success: true, filePath: '/tmp/a.zip' })
    await exportProject(PORTFOLIO_DOCUMENT)
    const { html } = await readEntries(stub.capturedBuffer!)
    expect(html).not.toMatch(/<html[^>]*\bdata-theme=/)
  })

  it('explicit auto is identical to omitting the option', async () => {
    const stub = setupElectronAPI({ success: true, filePath: '/tmp/a.zip' })
    await exportProject(PORTFOLIO_DOCUMENT, { theme: 'auto' })
    const { html } = await readEntries(stub.capturedBuffer!)
    expect(html).not.toMatch(/<html[^>]*\bdata-theme=/)
  })

  it('light stamps data-theme="light" on <html>', async () => {
    const stub = setupElectronAPI({ success: true, filePath: '/tmp/l.zip' })
    await exportProject(PORTFOLIO_DOCUMENT, { theme: 'light' })
    const { html } = await readEntries(stub.capturedBuffer!)
    expect(html).toMatch(/<html\b[^>]*\sdata-theme="light"/)
    // Single occurrence — no double-stamp.
    expect(html.match(/data-theme="light"/g)).toHaveLength(1)
  })

  it('dark stamps data-theme="dark" on <html>', async () => {
    const stub = setupElectronAPI({ success: true, filePath: '/tmp/d.zip' })
    await exportProject(PORTFOLIO_DOCUMENT, { theme: 'dark' })
    const { html } = await readEntries(stub.capturedBuffer!)
    expect(html).toMatch(/<html\b[^>]*\sdata-theme="dark"/)
  })

  it('survives minify (post-minify attribute order does not matter)', async () => {
    const stub = setupElectronAPI({ success: true, filePath: '/tmp/m.zip' })
    await exportProject(PORTFOLIO_DOCUMENT, { theme: 'dark', minify: true })
    const { html } = await readEntries(stub.capturedBuffer!)
    expect(html).toMatch(/data-theme="dark"/)
  })

  it('dry-run honors theme stamping', async () => {
    setupElectronAPI({ success: true, filePath: '/tmp/never.zip' })
    const result = await exportProject(PORTFOLIO_DOCUMENT, { dryRun: true, theme: 'light' })
    expect(result.html).toMatch(/<html\b[^>]*\sdata-theme="light"/)
  })
})

describe('includeSourceComments option (I-EXP-03)', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    vi.unstubAllGlobals()
  })

  it('omits the banner by default', async () => {
    const stub = setupElectronAPI({ success: true, filePath: '/tmp/x.zip' })
    await exportProject(PORTFOLIO_DOCUMENT)
    const { html, css } = await readEntries(stub.capturedBuffer!)
    expect(html).not.toContain('Generated by Draw-to-Web')
    expect(css).not.toContain('Generated by Draw-to-Web')
  })

  it('prepends a single-line banner to html + css when true', async () => {
    const stub = setupElectronAPI({ success: true, filePath: '/tmp/c.zip' })
    await exportProject(PORTFOLIO_DOCUMENT, { includeSourceComments: true })
    const { html, css } = await readEntries(stub.capturedBuffer!)
    expect(html).toContain('<!-- Generated by Draw-to-Web')
    expect(css.split('\n')[0]).toContain('/* Generated by Draw-to-Web')
    // Doctype must remain first on its own line.
    expect(html.trimStart().toLowerCase().startsWith('<!doctype html>')).toBe(true)
  })

  it('banner survives minify (applied after the minify stage)', async () => {
    const stub = setupElectronAPI({ success: true, filePath: '/tmp/cm.zip' })
    await exportProject(PORTFOLIO_DOCUMENT, { includeSourceComments: true, minify: true })
    const { html, css } = await readEntries(stub.capturedBuffer!)
    expect(html).toContain('Generated by Draw-to-Web')
    expect(css).toContain('Generated by Draw-to-Web')
  })

  it('banner appears in JS bundle when scripts.js is non-empty', async () => {
    const docWithJs = {
      ...PORTFOLIO_DOCUMENT,
      runtime: { ...PORTFOLIO_DOCUMENT.runtime, themeToggle: true },
    }
    const stub = setupElectronAPI({ success: true, filePath: '/tmp/j.zip' })
    await exportProject(docWithJs, { includeSourceComments: true })
    const { js } = await readEntries(stub.capturedBuffer!)
    expect(js).toBeDefined()
    expect(js!.split('\n')[0]).toContain('/* Generated by Draw-to-Web')
  })

  it('dry-run honors source comments', async () => {
    setupElectronAPI({ success: true, filePath: '/tmp/never.zip' })
    const result = await exportProject(PORTFOLIO_DOCUMENT, {
      dryRun: true,
      includeSourceComments: true,
    })
    expect(result.html).toContain('Generated by Draw-to-Web')
    expect(result.css).toContain('Generated by Draw-to-Web')
  })
})
